FROM openjdk:17-alpine

MAINTAINER 2024_6SOAT

ARG AWS_ACCESS_KEY2
ARG AWS_SECRET_ACCESS2

ENV ENV_VAR_FROM_ACTIONS=${AWS_ACCESS_KEY2}
ENV ANOTHER_VAR=${AWS_SECRET_ACCESS2}

COPY ./target/shogun-lanches-cliente-1.jar app.jar

ENV SPRING_PROFILES_ACTIVE=prod

ENTRYPOINT ["java", "-jar", "/app.jar"]

EXPOSE 8080