apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cliente-deployment
  labels:
    app: app-cliente-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-cliente-pod
  template:
    metadata:
      labels:
        app: app-cliente-pod
    spec:
      serviceAccountName: dynamodb-access-sa
      containers:
        - name: app-cliente-container
          image: 6soatgroup74/shogun-lanches-cliente:prod
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-cliente-configmap
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
          startupProbe:
            httpGet:
              path: actuator/health
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 500m